format = """
      #o#
    ####o#
 #o# \\\\#|_#,#
  ###\\\\ |/   #o#
   # {}{      #
      }{{
     ,'  `
$time $username$hostname$directory$git_branch$git_status$nodejs$rust$python$lua$golang$java$php$docker_context$haskell$perl$swift$kotlin$zig$elixir$memory_usage$cmd_duration
$custom
$character"""

palette = "gruvbox_dark"

[palettes.gruvbox_dark]
bg = "#282828"
fg = "#ebdbb2"
orange = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
red = "#fb4934"
aqua = "#8ec07c"
gray = "#a89984"
blue = "#83a598"
purple = "#d3869b"

[username]
# Add a dark background color with padding spaces before and after
style_user = "fg:blue bold bg:#ebdbb2"
style_root = "fg:red bold bg:#ebdbb2"
format = "[ $user]($style)"  # two spaces before and after for pill shape
show_always = true

[hostname]
ssh_only = false
style = "fg:purple bold bg:#ebdbb2"
format = "[@$hostname ]($style)"  # spaces to pad the pill shape
disabled = false


[directory]
style = "fg:green bold"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = false
format = "[ $path]($style)[$read_only](fg:red) "

[git_branch]
symbol = "󰘬 "
style = "fg:orange bold"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:aqua"
conflicted = "󰅙 "
ahead = "󰜷 ${count} "
behind = "󰜮 ${count} "
diverged = "󰹺 ${ahead_count}󰜮 ${behind_count} "
untracked = "󰋗 ${count} "
stashed = "󰏗 ${count} "
modified = "󰏫 ${count} "
staged = "󰐗 ${count} "
renamed = "󰑕 ${count} "
deleted = "󰍴 ${count} "

[nodejs]
symbol = "󰎙 "
style = "fg:green bold"
format = "[$symbol$version]($style) "

[rust]
symbol = "󱘗 "
style = "fg:red bold"
format = "[$symbol$version]($style) "

[python]
symbol = "󰌠 "
style = "fg:yellow bold"
format = "[$symbol$version]($style) "

[lua]
symbol = "󰢱 "
style = "fg:blue bold"
format = "[$symbol$version]($style) "

[golang]
symbol = "󰟓 "
style = "fg:aqua bold"
format = "[$symbol$version]($style) "

[java]
symbol = "󰬷 "
style = "fg:orange bold"
format = "[$symbol$version]($style) "

[php]
symbol = "󰌟 "
style = "fg:purple bold"
format = "[$symbol$version]($style) "

[docker_context]
symbol = "󰡨 "
style = "fg:blue bold"
format = "[$symbol$context]($style) "

[haskell]
symbol = " "
style = "fg:gray bold"
format = "[$symbol$version]($style) "

[perl]
symbol = " "
style = "fg:yellow bold"
format = "[$symbol$version]($style) "

[swift]
symbol = " "
style = "fg:orange bold"
format = "[$symbol$version]($style) "

[kotlin]
symbol = " "
style = "fg:blue bold"
format = "[$symbol$version]($style) "

[zig]
symbol = " "
style = "fg:yellow bold"
format = "[$symbol$version]($style) "

[elixir]
symbol = " "
style = "fg:purple bold"
format = "[$symbol$version]($style) "

[memory_usage]
symbol = "󰾆 "
style = "fg:red"
format = "[$symbol$ram_pct]($style) "
disabled = false
threshold = 70

[cmd_duration]
min_time = 2000
style = "fg:purple"
format = "[󰔛 $duration]($style) "

[time]
disabled = false
time_format = "%I:%M %p"
style = "fg:yellow italic"
format = "[$time]($style)"

[custom.uptime]
command = "uptime -p | sed 's/up //'"
when = "true"
style = "fg:gray italic"
format = "[$output]($style)"

[character]
success_symbol = "[ ●](bold green)"
error_symbol = "[ ●](bold red)"
vimcmd_symbol = "[ ●](bold yellow)"